import { useEffect, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { BookOpen, Heart, Image, Plus, Save, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

type Resource = { title: string; text: string; downloadUrl?: string };
type Resident = { name: string; text: string; image: string };
type DonationMethod = { emoji: string; title: string; description: string; fields: { label: string; value: string; copyable?: boolean }[]; link?: { text: string; url: string }; note?: string };
const DEFAULT_RESOURCES: Resource[] = [
  { title: 'Preparar tu hogar', text: 'Una lista sencilla para recibir a un perrito y facilitar sus primeros días.', downloadUrl: '' },
  { title: 'Tenencia responsable', text: 'Rutinas, salud preventiva, identificación y compromiso para toda la vida.', downloadUrl: '' },
  { title: 'Adaptación y confianza', text: 'Ideas para acompañar miedos, cambios de conducta y nuevos vínculos.', downloadUrl: '' },
];
const DEFAULT_RESIDENTS: Resident[] = [
  { name: 'Residentes senior', text: 'Perritos que necesitan calma, rutina y cuidados constantes.', image: '' },
  { name: 'Cuidados especiales', text: 'Casos que requieren tratamiento o acompañamiento permanente.', image: '' },
];
const DEFAULT_METHODS: DonationMethod[] = [{ emoji: '💳', title: '', description: '', fields: [{ label: '', value: '', copyable: true }] }];

export function EditorialManagement() {
  const [resources, setResources] = useState<Resource[]>(DEFAULT_RESOURCES);
  const [residents, setResidents] = useState<Resident[]>(DEFAULT_RESIDENTS);
  const [methods, setMethods] = useState<DonationMethod[]>(DEFAULT_METHODS);
  const query = useQuery({ queryKey: ['admin-editorial-content'], queryFn: async () => { const { data, error } = await supabase.from('site_settings').select('key, value').in('key', ['resources_items', 'sanctuary_residents', 'donation_methods']); if (error) throw error; return Object.fromEntries((data ?? []).map((item) => [item.key, item.value])); } });
  useEffect(() => { const settings = query.data; if (!settings) return; try { const parsedResources = JSON.parse(settings.resources_items ?? 'null') as Resource[]; if (Array.isArray(parsedResources) && parsedResources.length) setResources(parsedResources); } catch { /* usar contenido inicial */ } try { const parsedResidents = JSON.parse(settings.sanctuary_residents ?? 'null') as Resident[]; if (Array.isArray(parsedResidents) && parsedResidents.length) setResidents(parsedResidents); } catch { /* usar contenido inicial */ } try { const parsedMethods = JSON.parse(settings.donation_methods ?? 'null') as DonationMethod[]; if (Array.isArray(parsedMethods) && parsedMethods.length) setMethods(parsedMethods); } catch { /* mantener vacío hasta verificar datos */ } }, [query.data]);
  const save = useMutation({ mutationFn: async () => { const cleanResources = resources.map((item) => ({ title: item.title.trim(), text: item.text.trim(), downloadUrl: item.downloadUrl?.trim() || '' })).filter((item) => item.title && item.text); const cleanResidents = residents.map((item) => ({ name: item.name.trim(), text: item.text.trim(), image: item.image.trim() })).filter((item) => item.name && item.text); const cleanMethods = methods.map((method) => ({ ...method, title: method.title.trim(), description: method.description.trim(), fields: method.fields.map((field) => ({ ...field, label: field.label.trim(), value: field.value.trim() })).filter((field) => field.label && field.value) })).filter((method) => method.title && method.description && method.fields.length); if (!cleanResources.length || !cleanResidents.length) throw new Error('Debe existir al menos un recurso y un residente válidos.'); const { error } = await supabase.from('site_settings').upsert([{ key: 'resources_items', value: JSON.stringify(cleanResources) }, { key: 'sanctuary_residents', value: JSON.stringify(cleanResidents) }, { key: 'donation_methods', value: JSON.stringify(cleanMethods) }], { onConflict: 'key' }); if (error) throw error; }, onSuccess: () => toast.success('Contenido editorial actualizado.'), onError: (error: Error) => toast.error(error.message || 'No se pudo guardar el contenido.') });
  return <section className="space-y-6" aria-labelledby="editorial-title"><div><h1 id="editorial-title" className="flex items-center gap-2 font-heading text-2xl font-bold"><BookOpen className="h-6 w-6 text-[var(--color-primary)]" />Contenido editorial</h1><p className="mt-1 text-sm text-[var(--color-muted-foreground)]">Edita las tarjetas educativas y los residentes que aparecen en el sitio público.</p></div>
    {query.error && <div role="alert" className="rounded-xl border border-rose-300 bg-rose-50 p-4 text-sm text-rose-900 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-100">No se pudo cargar el contenido editorial desde Supabase.</div>}
    <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="flex items-center gap-2 text-base"><BookOpen className="h-5 w-5 text-[var(--color-primary)]" />Recursos educativos</CardTitle><Button variant="outline" size="sm" onClick={() => setResources([...resources, { title: '', text: '', downloadUrl: '' }])}><Plus className="mr-1 h-4 w-4" />Añadir</Button></CardHeader><CardContent className="space-y-4">{resources.map((resource, index) => <div key={index} className="grid gap-3 rounded-xl border border-[var(--color-border)] p-4 md:grid-cols-[.65fr_1fr_1fr_auto]"><div><Label htmlFor={`resource-title-${index}`}>Título</Label><Input id={`resource-title-${index}`} value={resource.title} onChange={(event) => setResources(resources.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item))} /></div><div><Label htmlFor={`resource-text-${index}`}>Descripción</Label><Textarea id={`resource-text-${index}`} rows={2} value={resource.text} onChange={(event) => setResources(resources.map((item, itemIndex) => itemIndex === index ? { ...item, text: event.target.value } : item))} /></div><div><Label htmlFor={`resource-download-${index}`}>Descargable</Label><Input id={`resource-download-${index}`} value={resource.downloadUrl ?? ''} onChange={(event) => setResources(resources.map((item, itemIndex) => itemIndex === index ? { ...item, downloadUrl: event.target.value } : item))} placeholder="URL del PDF" /></div><Button variant="ghost" size="icon" onClick={() => setResources(resources.filter((_, itemIndex) => itemIndex !== index))} disabled={resources.length === 1} aria-label="Eliminar recurso"><Trash2 className="h-4 w-4" /></Button></div>)}</CardContent></Card>
    <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="flex items-center gap-2 text-base"><Heart className="h-5 w-5 text-[var(--color-primary)]" />Residentes del Santuario</CardTitle><Button variant="outline" size="sm" onClick={() => setResidents([...residents, { name: '', text: '', image: '' }])}><Plus className="mr-1 h-4 w-4" />Añadir</Button></CardHeader><CardContent className="space-y-4">{residents.map((resident, index) => <div key={index} className="grid gap-3 rounded-xl border border-[var(--color-border)] p-4 md:grid-cols-[.65fr_1fr_1fr_auto]"><div><Label htmlFor={`resident-name-${index}`}>Nombre o grupo</Label><Input id={`resident-name-${index}`} value={resident.name} onChange={(event) => setResidents(residents.map((item, itemIndex) => itemIndex === index ? { ...item, name: event.target.value } : item))} /></div><div><Label htmlFor={`resident-text-${index}`}>Descripción</Label><Textarea id={`resident-text-${index}`} rows={2} value={resident.text} onChange={(event) => setResidents(residents.map((item, itemIndex) => itemIndex === index ? { ...item, text: event.target.value } : item))} /></div><div><Label htmlFor={`resident-image-${index}`}>Imagen</Label><div className="relative"><Image className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--color-muted-foreground)]" /><Input id={`resident-image-${index}`} className="pl-9" value={resident.image} onChange={(event) => setResidents(residents.map((item, itemIndex) => itemIndex === index ? { ...item, image: event.target.value } : item))} placeholder="URL o ruta pública" /></div></div><Button variant="ghost" size="icon" onClick={() => setResidents(residents.filter((_, itemIndex) => itemIndex !== index))} disabled={residents.length === 1} aria-label="Eliminar residente"><Trash2 className="h-4 w-4" /></Button></div>)}</CardContent></Card>
    <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-base">Métodos de donación verificados</CardTitle><Button variant="outline" size="sm" onClick={() => setMethods([...methods, { emoji: '💳', title: '', description: '', fields: [{ label: '', value: '', copyable: true }] }])}><Plus className="mr-1 h-4 w-4" />Añadir</Button></CardHeader><CardContent className="space-y-4">{methods.map((method, index) => <div key={index} className="space-y-3 rounded-xl border border-[var(--color-border)] p-4"><div className="grid gap-3 md:grid-cols-[auto_1fr_1fr]"><div><Label htmlFor={`method-emoji-${index}`}>Ícono</Label><Input id={`method-emoji-${index}`} className="w-20" value={method.emoji} onChange={(event) => setMethods(methods.map((item, itemIndex) => itemIndex === index ? { ...item, emoji: event.target.value } : item))} /></div><div><Label htmlFor={`method-title-${index}`}>Título</Label><Input id={`method-title-${index}`} value={method.title} onChange={(event) => setMethods(methods.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item))} /></div><div><Label htmlFor={`method-description-${index}`}>Descripción</Label><Input id={`method-description-${index}`} value={method.description} onChange={(event) => setMethods(methods.map((item, itemIndex) => itemIndex === index ? { ...item, description: event.target.value } : item))} /></div></div><div className="space-y-2">{method.fields.map((field, fieldIndex) => <div key={fieldIndex} className="grid gap-2 md:grid-cols-[1fr_1fr_auto]"><Input aria-label="Etiqueta del método" placeholder="Etiqueta" value={field.label} onChange={(event) => setMethods(methods.map((item, itemIndex) => itemIndex === index ? { ...item, fields: item.fields.map((current, currentIndex) => currentIndex === fieldIndex ? { ...current, label: event.target.value } : current) } : item))} /><Input aria-label="Valor del método" placeholder="Dato oficial" value={field.value} onChange={(event) => setMethods(methods.map((item, itemIndex) => itemIndex === index ? { ...item, fields: item.fields.map((current, currentIndex) => currentIndex === fieldIndex ? { ...current, value: event.target.value } : current) } : item))} /><Button type="button" variant="ghost" size="sm" onClick={() => setMethods(methods.map((item, itemIndex) => itemIndex === index ? { ...item, fields: item.fields.filter((_, currentIndex) => currentIndex !== fieldIndex) } : item))}>Quitar</Button></div>)}<Button type="button" variant="outline" size="sm" onClick={() => setMethods(methods.map((item, itemIndex) => itemIndex === index ? { ...item, fields: [...item.fields, { label: '', value: '', copyable: true }] } : item))}>Añadir dato</Button></div><Button type="button" variant="ghost" size="sm" onClick={() => setMethods(methods.filter((_, itemIndex) => itemIndex !== index))} disabled={methods.length === 1}>Eliminar método</Button></div>)}</CardContent></Card>
    <Button variant="warm" onClick={() => save.mutate()} disabled={save.isPending || query.isLoading}><Save className="mr-2 h-4 w-4" />{save.isPending ? 'Guardando…' : 'Guardar contenido editorial'}</Button>
  </section>;
}
