import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BookHeart, Edit3, Plus, Save, X } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

type Story = { id: string; animal_name: string; adopter_name: string; title: string; story: string; after_image_url: string; adoption_date: string; is_featured: boolean };
type StoryForm = Omit<Story, 'id'>;
const emptyForm: StoryForm = { animal_name: '', adopter_name: '', title: '', story: '', after_image_url: '', adoption_date: '', is_featured: false };

export function SuccessStoryManagement() {
  const qc = useQueryClient();
  const [editing, setEditing] = useState<string | null>(null);
  const [form, setForm] = useState<StoryForm>(emptyForm);
  const query = useQuery({ queryKey: ['admin-success-stories'], queryFn: async () => { const { data, error } = await supabase.from('success_stories').select('id, animal_name, adopter_name, title, story, after_image_url, adoption_date, is_featured').order('adoption_date', { ascending: false }); if (error) throw error; return (data ?? []) as Story[]; } });
  const save = useMutation({ mutationFn: async () => { const payload = { ...form, animal_name: form.animal_name.trim(), adopter_name: form.adopter_name.trim(), title: form.title.trim(), story: form.story.trim(), after_image_url: form.after_image_url.trim(), updated_at: new Date().toISOString() }; if (!payload.animal_name || !payload.title || payload.story.length < 20 || !payload.after_image_url || !payload.adoption_date) throw new Error('Completa nombre, título, historia, imagen y fecha.'); const request = editing === 'new' ? supabase.from('success_stories').insert(payload).select('id').single() : supabase.from('success_stories').update(payload).eq('id', editing).select('id').single(); const { data, error } = await request; if (error) throw error; if (!data) throw new Error('Supabase no confirmó la historia.'); }, onSuccess: () => { toast.success(editing === 'new' ? 'Historia creada.' : 'Historia actualizada.'); setEditing(null); void qc.invalidateQueries({ queryKey: ['admin-success-stories'] }); }, onError: (error: Error) => toast.error(error.message) });
  const startEdit = (story: Story) => { setEditing(story.id); setForm({ animal_name: story.animal_name, adopter_name: story.adopter_name, title: story.title, story: story.story, after_image_url: story.after_image_url, adoption_date: story.adoption_date, is_featured: story.is_featured }); };
  return <section className="space-y-6" aria-labelledby="stories-admin-title"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 id="stories-admin-title" className="flex items-center gap-2 font-heading text-2xl font-bold"><BookHeart className="h-6 w-6 text-[var(--color-primary)]" />Historias de éxito</h1><p className="mt-1 text-sm text-[var(--color-muted-foreground)]">Publica relatos reales de adopción para inspirar nuevas familias.</p></div><Button variant="warm" onClick={() => { setEditing('new'); setForm(emptyForm); }} disabled={Boolean(editing)}><Plus className="mr-2 h-4 w-4" />Nueva historia</Button></div>
    {query.error && <div role="alert" className="rounded-xl border border-rose-300 bg-rose-50 p-4 text-sm text-rose-900 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-100">No se pudieron cargar las historias. Verifica la tabla y sus políticas RLS.</div>}
    {editing && <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-base">{editing === 'new' ? 'Nueva historia' : 'Editar historia'}</CardTitle><Button variant="ghost" size="icon" onClick={() => setEditing(null)} aria-label="Cancelar"><X className="h-4 w-4" /></Button></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><div><Label htmlFor="story-dog">Nombre del perrito</Label><Input id="story-dog" required value={form.animal_name} onChange={(event) => setForm({ ...form, animal_name: event.target.value })} /></div><div><Label htmlFor="story-family">Familia adoptante</Label><Input id="story-family" value={form.adopter_name} onChange={(event) => setForm({ ...form, adopter_name: event.target.value })} /></div><div className="md:col-span-2"><Label htmlFor="story-title">Título</Label><Input id="story-title" required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></div><div className="md:col-span-2"><Label htmlFor="story-body">Historia</Label><Textarea id="story-body" required rows={6} value={form.story} onChange={(event) => setForm({ ...form, story: event.target.value })} /></div><div><Label htmlFor="story-image">Imagen final</Label><Input id="story-image" required value={form.after_image_url} onChange={(event) => setForm({ ...form, after_image_url: event.target.value })} placeholder="URL de imagen" /></div><div><Label htmlFor="story-date">Fecha de adopción</Label><Input id="story-date" required type="date" value={form.adoption_date} onChange={(event) => setForm({ ...form, adoption_date: event.target.value })} /></div><label className="flex items-center gap-2 text-sm md:col-span-2"><input type="checkbox" checked={form.is_featured} onChange={(event) => setForm({ ...form, is_featured: event.target.checked })} className="h-4 w-4 accent-[var(--color-primary)]" />Destacar historia</label><Button type="submit" variant="warm" disabled={save.isPending} className="w-fit"><Save className="mr-2 h-4 w-4" />{save.isPending ? 'Guardando…' : 'Guardar historia'}</Button></form></CardContent></Card>}
    {!query.error && !query.isLoading && query.data?.length === 0 && <div className="rounded-2xl border border-dashed border-[var(--color-border)] p-10 text-center text-sm text-[var(--color-muted-foreground)]">Todavía no hay historias publicadas.</div>}
    <div className="grid gap-4 md:grid-cols-2">{query.data?.map((story) => <Card key={story.id}><CardContent className="space-y-3 p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-heading font-bold">{story.title}</h2><p className="text-sm text-[var(--color-primary)]">{story.animal_name} · {story.adopter_name || 'Familia no indicada'}</p></div><span className="text-xs text-[var(--color-muted-foreground)]">{story.is_featured ? 'Destacada' : 'Publicada'}</span></div><p className="line-clamp-3 text-sm text-[var(--color-muted-foreground)]">{story.story}</p><Button variant="outline" size="sm" onClick={() => startEdit(story)} disabled={Boolean(editing)}><Edit3 className="mr-1 h-4 w-4" />Editar historia</Button></CardContent></Card>)}</div>
  </section>;
}
