import { useEffect, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Plus, Save, Trash2, Users } from 'lucide-react';
import { toast } from 'sonner';
import { supabase } from '@/lib/supabase';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

type Member = { name: string; role: string; emoji: string };
const EMPTY: Member = { name: '', role: '', emoji: '🐾' };
export function TeamManagement() {
  const [members, setMembers] = useState<Member[]>([]);
  const query = useQuery({ queryKey: ['admin-about-team'], queryFn: async () => { const { data, error } = await supabase.from('site_settings').select('value').eq('key', 'about_team').maybeSingle(); if (error) throw error; return data?.value ?? '[]'; } });
  useEffect(() => { if (query.data) { try { const parsed = JSON.parse(query.data); if (Array.isArray(parsed)) setMembers(parsed); } catch { /* mantener vacío */ } } }, [query.data]);
  const save = useMutation({ mutationFn: async () => { const clean = members.map((member) => ({ name: member.name.trim(), role: member.role.trim(), emoji: member.emoji.trim() || '🐾' })).filter((member) => member.name && member.role); const { error } = await supabase.from('site_settings').upsert({ key: 'about_team', value: JSON.stringify(clean) }, { onConflict: 'key' }); if (error) throw error; }, onSuccess: () => toast.success('Equipo actualizado.'), onError: () => toast.error('No se pudo guardar el equipo.') });
  return <section className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 font-heading text-2xl font-bold"><Users className="h-6 w-6 text-[var(--color-primary)]" />Equipo</h1><p className="mt-1 text-sm text-[var(--color-muted-foreground)]">Publica únicamente nombres y cargos autorizados.</p></div><Button variant="outline" onClick={() => setMembers([...members, EMPTY])}><Plus className="mr-2 h-4 w-4" />Añadir persona</Button></div>{query.error && <div role="alert" className="rounded-xl border border-rose-300 bg-rose-50 p-4 text-sm text-rose-900">No se pudo cargar el equipo desde Supabase.</div>}<Card><CardHeader><CardTitle className="text-base">Personas visibles en “Nosotros”</CardTitle></CardHeader><CardContent className="space-y-4">{members.length ? members.map((member, index) => <div key={index} className="grid gap-3 rounded-xl border border-[var(--color-border)] p-4 md:grid-cols-[80px_1fr_1fr_auto]"><div><Label htmlFor={`team-emoji-${index}`}>Ícono</Label><Input id={`team-emoji-${index}`} value={member.emoji} onChange={(event) => setMembers(members.map((item, itemIndex) => itemIndex === index ? { ...item, emoji: event.target.value } : item))} /></div><div><Label htmlFor={`team-name-${index}`}>Nombre</Label><Input id={`team-name-${index}`} value={member.name} onChange={(event) => setMembers(members.map((item, itemIndex) => itemIndex === index ? { ...item, name: event.target.value } : item))} /></div><div><Label htmlFor={`team-role-${index}`}>Cargo</Label><Input id={`team-role-${index}`} value={member.role} onChange={(event) => setMembers(members.map((item, itemIndex) => itemIndex === index ? { ...item, role: event.target.value } : item))} /></div><Button variant="ghost" size="icon" onClick={() => setMembers(members.filter((_, itemIndex) => itemIndex !== index))} aria-label="Eliminar persona"><Trash2 className="h-4 w-4" /></Button></div>) : <p className="rounded-xl border border-dashed border-[var(--color-border)] p-8 text-center text-sm text-[var(--color-muted-foreground)]">No hay personas publicadas.</p>}</CardContent></Card><Button variant="warm" onClick={() => save.mutate()} disabled={save.isPending}><Save className="mr-2 h-4 w-4" />{save.isPending ? 'Guardando…' : 'Guardar equipo'}</Button></section>;
}
